services:
  db:
    image: pgvector/pgvector:pg16
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: thesis
    ports:
      - "5432:5432"